language: node_js
node_js: "8"
script: yarn pipeline
cache:
    directories:
        - "node_modules"
dist: trusty
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET
  region: "us-east-2"
  app: "Power Rankings"
  env: "PowerRankings-env"
  bucket_name: "aws-codedeploy-us-east-2"
notifications:
  email: false
  slack:
    rooms:
      - dover-boys:HekMr2x7RnLbKn5pCAKmqnLR
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>)"
      - "Repo: %{repository} - Branch: %{branch}"
      - "Build Status: %{result} in %{duration}"
      - "%{author}"
      - "%{commit_message}"
    on_success: always # default: always
    on_failure: always # default: always
